# PCA

# Old

https://www.pythonmorsels.com/making-auto-updating-attribute/

In [ ]:
import numpy as np
import pandas as pd
import ipywidgets as widgets
from chemtools.exploration import PrincipalComponentAnalysis as pca

In [ ]:
f = "icp.xlsx"
data = pd.ExcelFile(f)

shet = widgets.Dropdown(
    options=data.sheet_names,
    description='Data sheet:',
    disabled=False,
)
display(shet)


Dropdown(description='Data sheet:', options=('MATRICE DEI DATI',), value='MATRICE DEI DATI')

In [ ]:
df = pd.read_excel(f, sheet_name=shet.value)
df


CAMPIONI         Cr        Cu        Mo        Mn        Ni        Pb  \
0    graffetta   0.012097  0.012704  0.002444  0.208169  0.017511  0.002835   
1     orologio   0.034978  0.172011  0.010050  0.529800  0.069733  0.005294   
2         filo  13.853548  0.256657  1.849671  1.210907  5.640097  0.002278   
3   taglierino   0.048148  0.048881  0.008404  0.643808  0.048588  0.003300   
4     fascetta   0.306884  0.005591  0.003174  0.241652  0.018525  0.003074   
5       foglio  13.250971  0.060986  0.012153  0.419739  0.105570  0.002260   
6      siringa  15.549177  0.250666  0.368831  1.734079  7.103451  0.001649   
7       spillo   0.031947  0.024526  0.007279  0.550200  2.020916  0.004162   
8       filo_2   0.047820  0.049092  0.008041  0.108227  0.049431  0.003818   
9         lama   9.996651  0.012189  0.022664  0.702806  0.084975  0.003147   
10      penna    0.206072  0.017137  0.002721  0.285841  0.600677  0.005588   
11    trucioli   0.114131  0.127671  0.022456  1.032333  0.071577  0.188105   

           V  
0   0.000049  
1   0.001963  
2   0.043808  
3   0.064381  
4   0.003807  
5   0.094532  
6   0.052999  
7   0.001548  
8   0.047703  
9   0.026613  
10  0.002039  
11  0.002196

In [ ]:
pca=pca(df, variable_name_column=[1,7], sample_name_row=["CAMPIONI"])

In [ ]:
np.argmax(pca.PC_index[2, :] < pca.PC_index[2, :].mean())

2

In [ ]:
pca.eigenvalues_plot()

## Altri parametri PCA per numero minimo di PC

In [ ]:
from chemtools.preprocessing import matrix_variance

In [ ]:
sum_eig=pca.V.sum()
print(sum_eig)
exp_var=pca.V/sum_eig
print(exp_var)
mean_eig=pca.V.mean()
print(mean_eig)
num = sum(abs(exp_var - (mean_eig/sum_eig)))
print(num)
den = den = 2*(sum_eig - mean_eig)/sum_eig
print(den)
K=(num/den)
print(K)
print("\n")
KLtmp = (1 + (p-1)*(1-K))
print(KLtmp)
KL = round(KLtmp)
print(KL)
KPtmp = pca.V.size ** (1-K)
KP = round(KPtmp)
print(KP)


6.000000000000001
[0.62261273 0.20125269 0.082616   0.05619659 0.0088393  0.02848269]
1.0000000000000002
0.9810641755348972
1.6666666666666667
0.5886385053209383




NameError: name 'p' is not defined

In [ ]:
variance_m=matrix_variance(pca.x)
variance_m

array([[ 0.16666667,  0.09464552,  0.09326822,  0.1091773 ,  0.11401943,
        -0.03739764],
       [ 0.09464552,  0.16666667,  0.1147372 ,  0.13650438,  0.13038941,
         0.02203795],
       [ 0.09326822,  0.1147372 ,  0.16666667,  0.08721288,  0.11663185,
        -0.01829091],
       [ 0.1091773 ,  0.13650438,  0.08721288,  0.16666667,  0.13727747,
         0.04135398],
       [ 0.11401943,  0.13038941,  0.11663185,  0.13727747,  0.16666667,
        -0.02860526],
       [-0.03739764,  0.02203795, -0.01829091,  0.04135398, -0.02860526,
         0.16666667]])

In [ ]:
eigenvalue=pca.V
p = pca.V.size
x=pca.correlation_matrix
j= pca.V.size

In [ ]:
n = np.linalg.matrix_rank(variance_m)
n

6

In [ ]:
EV=[]
for i in range(pca.V.size):
    EV = np.append(EV,eigenvalue[i]/(eigenvalue.sum()))
EV


array([0.62261273, 0.20125269, 0.082616  , 0.05619659, 0.0088393 ,
       0.02848269])

In [ ]:
(EV-(1/(pca.V.size))).sum() #numeratore


0.0

In [ ]:
2*(pca.V.size-1)/pca.V.size #denominatore


1.6666666666666667

In [ ]:
K=(EV-1/(pca.V.size)).sum()/(2*(pca.V.size-1)/pca.V.size)
k


NameError: name 'k' is not defined

In [ ]:
round(1+(j-1)*(1-k))


NameError: name 'k' is not defined

In [ ]:
a = sum(eigenvalue[m]/eigenvalue.sum()-1/p for m in range(n))
a

0.0

In [ ]:
k=(a+(p-n)**(1/p))/(2*(p-1)/p)
k

0.0

In [ ]:
kl=round(1+(j-1)*(1-k))
kl

6

In [ ]:
kp=round(j**(1-k))
kp

6

https://www.sciencedirect.com/science/article/pii/S0169743998001245
https://www.academia.edu/6648469/The_K_correlation_index_theory_development_and_its_application_in_chemometrics
https://www.youtube.com/watch?v=JtrPvAdVJiM&ab_channel=Mattoscacco

# New

In [ ]:
from chemtools.preprocessing import autoscaling

class PrincipalComponentAnalysis:
    def __init__(self,X):
        self.X=X
    
    def fit(self):
        # Calcola la media
        self.mean = np.mean(X, axis=0)
        # Calcola la matrice autoscalata
        self.X_autoscaled = autoscaling(self.X)

In [ ]:
#mi scrivi una classe python, usando numpy e le formule matriciali, per eseguire una principal components analysis?
class PCA:
    def __init__(self, n_components):
        self.n_components = n_components
        self.components = None
        self.mean = None

    def fit(self, X):
        # Calcola la media
        self.mean = np.mean(X, axis=0)
        X = X - self.mean

        # Calcola la matrice di covarianza
        cov = np.cov(X.T)

        # Calcola gli autovettori e gli autovalori
        eigenvalues, eigenvectors = np.linalg.eig(cov)

        # Ordina gli autovettori
        eigenvectors = eigenvectors.T
        idxs = np.argsort(eigenvalues)[::-1]
        eigenvalues = eigenvalues[idxs]
        eigenvectors = eigenvectors[idxs]

        # Memorizza i primi n autovettori
        self.components = eigenvectors[0:self.n_components]

    def transform(self, X):
        # Proietta i dati
        X = X - self.mean
        return np.dot(X, self.components.T)